name: Build ly_cyberpunk

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: dependencies
      run: sudo apt-get install -y build-essential libpam0g-dev libxcb-xkb-dev
    - name: make
      run: make
